CREATE TABLE learning_materials (
    id CHAR(36) NOT NULL,
    user_id CHAR(36) NOT NULL,
    learning_space_id CHAR(36) NOT NULL,
    original_name VARCHAR(255) NOT NULL,
    object_key VARCHAR(768) NOT NULL,
    mime_type VARCHAR(100) NOT NULL,
    size_bytes BIGINT UNSIGNED NOT NULL,
    content_sha256 BINARY(32) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'queued',
    failure_reason VARCHAR(1000) NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uk_materials_object_key (object_key),
    KEY idx_materials_space_created (learning_space_id, created_at),
    KEY idx_materials_user_status (user_id, status),
    CONSTRAINT fk_materials_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_materials_space FOREIGN KEY (learning_space_id) REFERENCES learning_spaces (id) ON DELETE CASCADE,
    CONSTRAINT chk_materials_status CHECK (status IN ('queued', 'processing', 'ready', 'failed')),
    CONSTRAINT chk_materials_size CHECK (size_bytes > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE generation_jobs (
    id CHAR(36) NOT NULL,
    user_id CHAR(36) NOT NULL,
    learning_space_id CHAR(36) NOT NULL,
    material_id CHAR(36) NOT NULL,
    job_type VARCHAR(40) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'queued',
    progress TINYINT UNSIGNED NOT NULL DEFAULT 0,
    attempts TINYINT UNSIGNED NOT NULL DEFAULT 0,
    max_attempts TINYINT UNSIGNED NOT NULL DEFAULT 3,
    available_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    started_at DATETIME(6) NULL,
    completed_at DATETIME(6) NULL,
    error_code VARCHAR(80) NULL,
    error_message VARCHAR(1000) NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    KEY idx_jobs_dispatch (status, available_at, created_at),
    KEY idx_jobs_material_created (material_id, created_at),
    KEY idx_jobs_user_space (user_id, learning_space_id),
    CONSTRAINT fk_jobs_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_jobs_space FOREIGN KEY (learning_space_id) REFERENCES learning_spaces (id) ON DELETE CASCADE,
    CONSTRAINT fk_jobs_material FOREIGN KEY (material_id) REFERENCES learning_materials (id) ON DELETE CASCADE,
    CONSTRAINT chk_jobs_type CHECK (job_type IN ('process_material')),
    CONSTRAINT chk_jobs_status CHECK (status IN ('queued', 'processing', 'succeeded', 'failed')),
    CONSTRAINT chk_jobs_progress CHECK (progress BETWEEN 0 AND 100),
    CONSTRAINT chk_jobs_attempts CHECK (attempts <= max_attempts)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
