CREATE TABLE material_chunks (
    id CHAR(36) NOT NULL,
    user_id CHAR(36) NOT NULL,
    learning_space_id CHAR(36) NOT NULL,
    material_id CHAR(36) NOT NULL,
    chunk_index INT UNSIGNED NOT NULL,
    content MEDIUMTEXT NOT NULL,
    source_type VARCHAR(20) NOT NULL,
    source_start INT UNSIGNED NULL,
    source_end INT UNSIGNED NULL,
    char_count INT UNSIGNED NOT NULL,
    token_estimate INT UNSIGNED NOT NULL,
    content_hash BINARY(32) NOT NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uk_chunks_material_index (material_id, chunk_index),
    KEY idx_chunks_space_material (learning_space_id, material_id),
    KEY idx_chunks_hash (content_hash),
    CONSTRAINT fk_chunks_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_chunks_space FOREIGN KEY (learning_space_id) REFERENCES learning_spaces (id) ON DELETE CASCADE,
    CONSTRAINT fk_chunks_material FOREIGN KEY (material_id) REFERENCES learning_materials (id) ON DELETE CASCADE,
    CONSTRAINT chk_chunks_source_type CHECK (source_type IN ('page', 'slide', 'document', 'text')),
    CONSTRAINT chk_chunks_char_count CHECK (char_count > 0),
    CONSTRAINT chk_chunks_token_estimate CHECK (token_estimate > 0),
    CONSTRAINT chk_chunks_source_range CHECK (source_end IS NULL OR source_start IS NULL OR source_end >= source_start)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
