CREATE TABLE chunk_embeddings (
    id CHAR(36) NOT NULL,
    user_id CHAR(36) NOT NULL,
    learning_space_id CHAR(36) NOT NULL,
    material_id CHAR(36) NOT NULL,
    chunk_id CHAR(36) NOT NULL,
    qdrant_point_id CHAR(36) NOT NULL,
    embedding_model VARCHAR(100) NOT NULL,
    vector_dimension SMALLINT UNSIGNED NOT NULL,
    content_hash BINARY(32) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'pending',
    failure_reason VARCHAR(1000) NULL,
    indexed_at DATETIME(6) NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uk_chunk_embeddings_chunk_model (chunk_id, embedding_model),
    UNIQUE KEY uk_chunk_embeddings_point (qdrant_point_id),
    KEY idx_chunk_embeddings_dispatch (status, created_at),
    KEY idx_chunk_embeddings_space (user_id, learning_space_id, status),
    KEY idx_chunk_embeddings_material (material_id, status),
    CONSTRAINT fk_chunk_embeddings_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_chunk_embeddings_space FOREIGN KEY (learning_space_id) REFERENCES learning_spaces (id) ON DELETE CASCADE,
    CONSTRAINT fk_chunk_embeddings_material FOREIGN KEY (material_id) REFERENCES learning_materials (id) ON DELETE CASCADE,
    CONSTRAINT fk_chunk_embeddings_chunk FOREIGN KEY (chunk_id) REFERENCES material_chunks (id) ON DELETE CASCADE,
    CONSTRAINT chk_chunk_embeddings_dimension CHECK (vector_dimension > 0),
    CONSTRAINT chk_chunk_embeddings_status CHECK (status IN ('pending', 'indexed', 'failed'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
